[package]
name = "rars-format"
version = "0.1.0"
description = "RAR archive format parser and writer implementation used by rars."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
getrandom = "0.2"
rars-codec = { version = "0.1.0", path = "../rars-codec" }
rars-crypto = { version = "0.1.0", path = "../rars-crypto" }
rars-recovery = { version = "0.1.0", path = "../rars-recovery" }
