[package]
name = "rars-format"
version = "0.1.0"
description = "RAR archive format parser and writer implementation used by rars."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme = false
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
getrandom.workspace = true
rars-codec.workspace = true
rars-crypto.workspace = true
rars-recovery.workspace = true
