[package]
name = "rars-crypto"
version = "0.1.0"
description = "RAR legacy and modern archive encryption primitives."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme = false
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
categories = ["cryptography"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
aes.workspace = true
hmac.workspace = true
sha1.workspace = true
sha2.workspace = true
